[package]
name = "sargon-hash"
version = "1.1.99"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
sargon-bytes = { path = "../sargon-bytes" }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
serde = { workspace = true }
