[package]
name = "sargon-uniffi"
# Don't forget to update version in crates/sargon/Cargo.toml
version = "1.2.1"
edition = "2021"
build = "build.rs"

[[test]]
name = "vectors"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[[bin]]
name = "sargon-bindgen"
path = "src/bindgen/bin.rs"
# required-features = ["build-binary"]

[dependencies]
# === SARGON CRATES ===
sargon-core = { path = "../sargon-core" }
sargon = { path = "../sargon" }
sargon-manifests = { path = "../sargon-manifests" }
sargon-uniffi-conversion-macros = { path = "../sargon-uniffi-conversion-macros" }

# === RADIX DEPENDENCIES ===
radix-engine-toolkit = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
assert-json-diff = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
camino = { workspace = true }
clap = { workspace = true }
delegate = { workspace = true }
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
hex = { workspace = true }
iso8601-timestamp = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
preinterpret = { workspace = true }
pretty_assertions = { workspace = true }
pretty_env_logger = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
uniffi = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }
uniffi = { workspace = true, features = ["bindgen-tests"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[lints.rust]
unexpected_cfgs = { level = "forbid", check-cfg = ['cfg(tarpaulin_include)'] }
