[package]
name = "sargon-hierarchical-deterministic"
version = "1.1.99"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
identified-vec-of = { path = "../identified-vec-of" }
sargon-core = { path = "../sargon-core" }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }
radix-engine-interface = { workspace = true }
radix-rust = { workspace = true }
radix-transactions = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
assert-json-diff = { workspace = true }
bip39 = { workspace = true }
delegate = { workspace = true }
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
iota-crypto = { workspace = true }
iso8601-timestamp = { workspace = true }
itertools = { workspace = true }
k256 = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }
