[package]
name = "sargon-hierarchical-deterministic"
version = "1.2.0"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
sargon-core = { path = "../sargon-core" }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }
radix-engine-interface = { workspace = true }
radix-rust = { workspace = true }
radix-transactions = { workspace = true }


# ==== EXTERNAL DEPENDENCIES ====
assert-json-diff = { workspace = true }
delegate = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
hkdf = { workspace = true }
hex = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
derive_more = { workspace = true }


itertools = { workspace = true }
iota-crypto = { workspace = true }
k256 = { workspace = true }
rand = { workspace = true }
log = { workspace = true }


serde_with = { workspace = true }

paste = { workspace = true }
serde_repr = { workspace = true }
iso8601-timestamp = { workspace = true }
zeroize = { workspace = true }
strum = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }

uuid = { workspace = true }

# bip39 = "2.0.0"
bip39 = { git = "https://github.com/rust-bitcoin/rust-bip39", rev = "a30760beac21d595b2bda376df4f4e6bf029bcc5", features = [
    "serde",
    "zeroize",
    "french",
] }