[package]
name = "sargon-hierarchical-deterministic"
version = "1.1.99"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
identified-vec-of = { path = "../identified-vec-of" }
sargon-core = { path = "../sargon-core" }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
bip39 = { workspace = true }
derive_more = { workspace = true }
enum-iterator = { workspace = true }
iota-crypto = { workspace = true }
itertools = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
zeroize = { workspace = true }
