[package]
name = "sargon-core-error"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===


# === RADIX DEPENDENCIES ===

# === EXTERNAL DEPENDENCIES ===
log = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
