[package]
name = "sargon-transaction-models"
version = "1.2.1"
edition = "2021"
build = "build.rs"

[dependencies]
sargon-core = { path = "../sargon-core" }
identified-vec-of = { path = "../identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-factors = { path = "../sargon-factors" }
sargon-addresses = { path = "../sargon-addresses" }

# == Radix dependencies ==
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.3.0" }
radix-rust = { workspace = true }
radix-engine = { workspace = true }
radix-common = { workspace = true }
radix-common-derive = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.3.0" }
radix-engine-interface = { workspace = true }
radix-engine-toolkit-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.3.0" }
radix-transactions = { workspace = true }
radix-engine-toolkit = { workspace = true }

# == External Dependencies ==
zeroize = { workspace = true }
log = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
serde_repr = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
iso8601-timestamp = { workspace = true }
uuid = { workspace = true }
strum = { workspace = true }
enum-iterator = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
delegate = { workspace = true }
itertools = { workspace = true }
enum-as-inner = { workspace = true }
iota-crypto = { workspace = true }
k256 = { workspace = true }
assert-json-diff = { workspace = true }
url = { workspace = true }
paste = { workspace = true }
async-trait = { workspace = true }
pretty_assertions = { workspace = true }

[build-dependencies]
cargo_toml = { workspace = true }
