[package]
name = "sargon-transaction-models"
version = "1.1.99"
edition = "2021"
build = "build.rs"

[dependencies]
# === SARGON CRATES ===
identified-vec-of = { path = "../identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-factors = { path = "../sargon-factors" }
sargon-addresses = { path = "../sargon-addresses" }
sargon-hash = { path = "../sargon-hash" }
sargon-bytes = { path = "../sargon-bytes" }
sargon-ecc = { path = "../sargon-ecc" }
sargon-numeric = { path = "../sargon-numeric" }
sargon-has-sample-values = { path = "../sargon-has-sample-values" }
sargon-core-metadata = { path = "../sargon-core-metadata" }
sargon-core-network = { path = "../sargon-core-network" }
sargon-core-utils = { path = "../sargon-core-utils" }
sargon-core-tx = { path = "../sargon-core-tx" }
sargon-core-collections = { path = "../sargon-core-collections" }
sargon-core-misc = { path = "../sargon-core-misc" }                                   # Instant

# === RADIX DEPENDENCIES ===
radix-common = { workspace = true }
radix-common-derive = { workspace = true }
radix-engine = { workspace = true }
radix-engine-interface = { workspace = true }
radix-engine-toolkit = { workspace = true }
radix-engine-toolkit-common = { workspace = true }
radix-rust = { workspace = true }
radix-transactions = { workspace = true }
sbor = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-iterator = { workspace = true }
enum-as-inner = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }

[build-dependencies]
cargo_toml = { workspace = true }
