[package]
name = "prelude"
version = "1.2.11"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
# None

# === RADIX DEPENDENCIES ===
radix-engine = { workspace = true }
radix-engine-toolkit = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
