[package]
name = "sargon-factors"
version = "1.1.99"
edition = "2021"
build = "build.rs"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
identified-vec-of = { path = "../identified-vec-of" }
sargon-core = { path = "../sargon-core" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }
radix-engine-interface = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
enum-iterator = { workspace = true }
hkdf = { workspace = true }
iota-crypto = { workspace = true }
k256 = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
zeroize = { workspace = true }
