[package]
name = "sargon-core-utils"
version = "1.2.1"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
sargon-core-error = { path = "../sargon-core-error" }

# === EXTERNAL DEPENDENCIES ===
iso8601-timestamp = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
