[package]
name = "profile-persona-data"
version = "1.2.8"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
addresses = { workspace = true }
core-misc = { workspace = true }
short-string = { workspace = true }
entity-foundation = { workspace = true }
identified-vec-of = { workspace = true }
network = { workspace = true }
has-sample-values = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
