[package]
name = "profile-persona-data"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
assert-json = { path = "../../../core/assert-json" }
addresses = { path = "../../../crypto/addresses" }
core-misc = { path = "../../../core/misc" }
short-string = { path = "../../../common/short-string" }
entity-foundation = { path = "../../../common/entity-foundation" }
identified-vec-of = { path = "../../../common/identified-vec-of" }
network = { path = "../../../common/network" }
has-sample-values = { path = "../../../core/has-sample-values" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
