[package]
name = "sargon-profile-app-preferences"
version = "1.1.99"
edition = "2021"

[dependencies]
# === INTERNAL DEPENDENCIES ===
identified-vec-of = { path = "../../../types/identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../../../crypto/hd" }
sargon-factors = { path = "../../../factors/factors" }
sargon-numeric = { path = "../../../types/numeric" }
sargon-core-misc = { path = "../../../core/misc" }                                     # decl_bool_Type
sargon-keys-collector = { path = "../../../factors/keys-collector" }
sargon-addresses = { path = "../../../crypto/addresses" }
sargon-transaction-models = { path = "../../../transaction/models" }
sargon-profile-gateway = { path = "../../../profile/models/gateway" }
sargon-profile-security-structures = { path = "../../../profile/models/security-structures" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
