[package]
name = "sargon"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
strum_macros = { workspace = true }
iso8601-timestamp = { workspace = true }
uuid = { workspace = true }
serde_repr = { workspace = true }
strum = { workspace = true }
radix-engine-common = { workspace = true }
radix-engine-toolkit-json = { workspace = true }
radix-engine-toolkit = { workspace = true }
radix-engine-interface = { workspace = true }
enum-iterator = { workspace = true }
hex = { workspace = true }
transaction = { workspace = true }
bip32 = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
enum-as-inner = { workspace = true }
identified_vec = { workspace = true }
schemars = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
uniffi = { workspace = true, features = ["cli"] }
url = { git = "https://github.com/sajjon/rust-url", branch = "uniffi", features = [
    "serde",
    "uniffi",
] }
pretty_assertions = "1.4.0"
slip10 = "0.4.3"
memoize = "0.4.1"
itertools = { version = "0.12.0" }
bip39 = { version = "2.0.0", features = ["serde"] }
time-util = { version = "0.3.4", features = ["chrono"] }
derive_more = { workspace = true }
delegate = { workspace = true }
assert-json-diff = "2.0.2"

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[dev-dependencies]
uniffi = { workspace = true, features = ["bindgen-tests"] }
serde = { workspace = true }

[[test]]
name = "vectors"

[[test]]
name = "uniffi"
test = false

[lib]
crate-type = ["staticlib", "cdylib", "lib"]
