[package]
name = "sargon-factors-supporting-types"
version = "1.2.1"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
identified-vec-of = { path = "../identified-vec-of" }
sargon-core = { path = "../sargon-core" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-factors = { path = "../sargon-factors" }


# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
async-trait = { workspace = true }
