[all]
exclude-files = [
    "crates/sargon/src/lib.rs",
    # Too many false negatives (macro usage)
    "crates/sargon/src/profile/v100/address/non_fungible_resource_address.rs",
    "crates/sargon/src/profile/v100/address/wrap_ret_address.rs",
    "crates/sargon/src/wrapped_radix_engine_toolkit/high_level/sargon_specific_types/address_union.rs",
    # Rest
    "crates/sargon/src/bindgen/*",
    "example/*",
    "target/*",
    "apple/*",
    ".swiftpm/*",
    "scripts/*",
    ".build/*",
    "Package.swift",
]
verbose = false
timeout = "2m"
force-clean = true
locked = true
all-features = true
jobs = 1
out = ["Xml"]
