[all]
exclude-files = [
    # Too many false negatives (macro usage)
    "src/profile/v100/address/non_fungible_resource_address.rs",
    "src/profile/v100/address/wrap_ret_address.rs",
    "src/wrapped_radix_engine_toolkit/high_level/sargon_specific_types/address_union.rs",
    # Rest
    "src/bindgen/*",
    "example/*",
    "target/*",
    "apple/*",
    ".swiftpm/*",
    "scripts/*",
    ".build/*",
    "Package.swift",
]
verbose = true
run-types = ["AllTargets"]
timeout = "15m"
force-clean = true
locked = true
all = true
jobs = 1
out = ["Xml"]
