[all]
exclude-files = [
    # Skip Uniffi crate, we rely on `crates/sargon` AND hosts being tested
    "crates/sargon-uniffi/*",
    # Skip Uniffi crate, we rely on hosts being tested
    "crates/sargon-uniffi-conversion-macros/*",

    "crates/sargon/src/lib.rs",
    # Too many false negatives (macro usage)
    "crates/profile/models/profile_SPLIT_ME/src/profile/v100/address/non_fungible_resource_address.rs",
    "crates/profile/models/profile_SPLIT_ME/src/profile/v100/address/wrap_ret_address.rs",
    "crates/crypto/addresses/src/address/address_union.rs",
    "crates/core/assert-json/src/assert_json.rs",
    # Rest
    "crates/sargon/src/bindgen/*",
    "example/*",
    "target/*",
    "apple/*",
    ".swiftpm/*",
    "scripts/*",
    ".build/*",
    "Package.swift",
]
verbose = false
timeout = "2m"
locked = true
all-features = true
jobs = 1
out = ["Html"]
