[all]
exclude-files = [
    # Too many false negatives (macro usage)
    "src/profile/v100/address/non_fungible_resource_address.rs",
    "src/profile/v100/address/wrap_ret_address.rs",
    # Rest
    "tests/*",
    "src/bindgen/*",
    "example/*",
    "target/*",
    "apple/*",
    ".swiftpm/*",
    "scripts/*",
    ".build/*",
    "Package.swift",
]
verbose = false
run-types = ["Lib"]
timeout = "5m"
skip-clean = true
out = ["Xml"]
