[files]
extend-exclude = [
    "fixtures/**",
    "scripts/**",
    "apple/Sources/UniFFI/Sargon.swift",
    "examples/iOS/Backend/Sources/Planbok/Features/DebugProfileFeature.swift",
    "tarpaulin-report.html",
]

[default.extend-identifiers]
inout = "inout"
hd = "hd"
pool_tdx_2_1c4ml86h8lvfk7jma0jy0vksh8srcxhmtax8nd3aur29qtd2k2wmlzk = "pool_tdx_2_1c4ml86h8lvfk7jma0jy0vksh8srcxhmtax8nd3aur29qtd2k2wmlzk"
account_sim1c8s2hass5g62ckwpv78y8ykdqljtetv4ve6etcz64gveykxznj36tr = "account_sim1c8s2hass5g62ckwpv78y8ykdqljtetv4ve6etcz64gveykxznj36tr"
resource_tdx_2_1thw7yclz24h5xjp3086cj8z2ya0d7p9mydk0yh68c28ha02uhzrnyy = "resource_tdx_2_1thw7yclz24h5xjp3086cj8z2ya0d7p9mydk0yh68c28ha02uhzrnyy"
resource_tdx_2_1ntuaekqexa73m9en04jj3vdt3fk9u9kdk8q9su4efldun2y7nd3cga = "resource_tdx_2_1ntuaekqexa73m9en04jj3vdt3fk9u9kdk8q9su4efldun2y7nd3cga"
package_tdx_2_1p4lftg7zjtmvyw5dwv3fg9cxyumlrya03p5uecqdge9thje4nm5qtk = "package_tdx_2_1p4lftg7zjtmvyw5dwv3fg9cxyumlrya03p5uecqdge9thje4nm5qtk"
account_tdx_2_12yf9gd53yfep7a669fv2t3wm7nz9zeezwd04n02a433ker8vza6rhe = "account_tdx_2_12yf9gd53yfep7a669fv2t3wm7nz9zeezwd04n02a433ker8vza6rhe"
resource_tdx_2_1th4gzm9rk5s28yf5gud0a32m082g4x60d6na4ecsccte032y3xu785 = "resource_tdx_2_1th4gzm9rk5s28yf5gud0a32m082g4x60d6na4ecsccte032y3xu785"
account_tdx_2_12xy3a3eme090gwzku277q0awutftu76nd4wddjvhtzelf84glmghae = "account_tdx_2_12xy3a3eme090gwzku277q0awutftu76nd4wddjvhtzelf84glmghae"
ec4892a8ba3b86f1 = "ec4892a8ba3b86f1"
f87611f279e0daa3 = "f87611f279e0daa3"
fo = "fo"
aer264 = "aer264"
imeAction = "imeAction"
ImeAction = "ImeAction"
evice = "evice"

[default.extend-words]
inout = "inout"
hd = "hd"
imeAction = "imeAction"
ImeAction = "ImeAction"
uiu = "uiu"
fo = "fo"
aer264 = "aer264"
