[files]
extend-exclude = [
    "scripts/**",
    "apple/Sources/UniFFI/Sargon.swift",
    "tarpaulin-report.html",
    "tests/vectors/fixtures/*.json",
]


[default.extend-identifiers]
inout = "inout"
pool_tdx_2_1c4ml86h8lvfk7jma0jy0vksh8srcxhmtax8nd3aur29qtd2k2wmlzk = "pool_tdx_2_1c4ml86h8lvfk7jma0jy0vksh8srcxhmtax8nd3aur29qtd2k2wmlzk"

[default.extend-words]
inout = "inout"
