[files]
extend-exclude = [
    "scripts/**",
    "apple/Sources/UniFFI/Sargon.swift",
    "tarpaulin-report.html",
    "tests/vectors/fixtures/*.json",
]


[default.extend-identifiers]
inout = "inout"

[default.extend-words]
inout = "inout"