[package]
name = "sargon-profile"
version = "1.1.99"
edition = "2021"
build = "build.rs"

[dependencies]
# === INTERNAL DEPENDENCIES ===
sargon-core = { path = "../sargon-core" }
identified-vec-of = { path = "../identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-factors = { path = "../sargon-factors" }
sargon-keys-collector = { path = "../sargon-keys-collector" }
sargon-addresses = { path = "../sargon-addresses" }
sargon-transaction-models = { path = "../sargon-transaction-models" }
sargon-profile-app-preferences = { path = "../sargon-profile-app-preferences" }
sargon-profile-security-structures = { path = "../sargon-profile-security-structures" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-iterator = { workspace = true }
hkdf = { workspace = true }
k256 = { workspace = true }
once_cell = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
strum = { workspace = true }

[build-dependencies]
cargo_toml = { workspace = true }
