[package]
name = "network"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
assert-json = { path = "../../core/assert-json" }
has-sample-values = { path = "../../core/has-sample-values" }
numeric = { path = "../../common/numeric" }

# === RADIX DEPENDENCIES ===
radix-common = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
enum-iterator = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
serde_repr = { workspace = true }
serde_json = { workspace = true }
