[package]
name = "network"
version = "1.2.5"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
has-sample-values = { workspace = true }
numeric = { workspace = true }

# === RADIX DEPENDENCIES ===
radix-common = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
enum-iterator = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
serde_repr = { workspace = true }
serde_json = { workspace = true }
