[package]
name = "gateway-models"
version = "1.1.99"
edition = "2021"
build = "build.rs"

[dependencies]
# === SARGON CRATES ===
sargon-core-assert-json = { path = "../../core/assert-json" }
sargon-addresses = { path = "../../crypto/addresses" }
sargon-transaction-models = { path = "../../transaction/models" }
sargon-core-misc = { path = "../../core/misc" } # decl_bool_type
sargon-core-metadata = { path = "../../types/metadata" }

# === RADIX DEPENDENCIES ===
radix-engine-toolkit-common = { workspace = true }
radix-transactions = { workspace = true }
radix-engine-interface = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
enum-as-inner = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
