[package]
name = "gateway-models"
version = "1.2.12"
edition = "2021"


[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
addresses = { workspace = true }
transaction-models = { workspace = true }
core-misc = { workspace = true }          # decl_bool_type
metadata = { workspace = true }

# === RADIX DEPENDENCIES ===
radix-engine-toolkit-common = { workspace = true }
radix-transactions = { workspace = true }
radix-engine-interface = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
enum-as-inner = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
