[package]
name = "sargon-profile-gateway"
version = "1.1.99"
edition = "2021"

[dependencies]
# === INTERNAL DEPENDENCIES ===
sargon-core = { path = "../sargon-core" }
identified-vec-of = { path = "../identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-factors = { path = "../sargon-factors" }
sargon-keys-collector = { path = "../sargon-keys-collector" }
sargon-addresses = { path = "../sargon-addresses" }
sargon-transaction-models = { path = "../sargon-transaction-models" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
