[package]
name = "sargon-profile-gateway"
version = "1.1.99"
edition = "2021"

[dependencies]
# === INTERNAL DEPENDENCIES ===
identified-vec-of = { path = "../identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-factors = { path = "../sargon-factors" }
sargon-keys-collector = { path = "../sargon-keys-collector" }
sargon-addresses = { path = "../sargon-addresses" }
sargon-transaction-models = { path = "../sargon-transaction-models" }
sargon-core-network = { path = "../sargon-core-network" }
sargon-core-error = { path = "../sargon-core-error" }
sargon-core-misc = { path = "../sargon-core-misc" }
sargon-core-assert-json = { path = "../sargon-core-assert-json" }
sargon-has-sample-values = { path = "../sargon-has-sample-values" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
