[package]
name = "sargon-os"
version = "1.2.6"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
profile = { workspace = true }
profile-logic = { workspace = true }
profile-state-holder = { workspace = true }
drivers = { workspace = true }
clients = { workspace = true }
build-info = { workspace = true }
interactors = { workspace = true }
sub-systems = { workspace = true }
host-info = { workspace = true }
key-derivation-traits = { workspace = true }
signing-traits = { workspace = true }
factor-instances-provider = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
async-trait = { workspace = true }
actix-rt = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
