[package]
name = "sargon-os"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
profile = { path = "../../../profile/models/profile_SPLIT_ME" }
profile-logic = { path = "../../../profile/logic/logic_SPLIT_ME" }
profile-state-holder = { path = "../../../system/profile-state-holder" }
drivers = { path = "../../../system/drivers" }
clients = { path = "../../../system/clients/clients" }
build-info = { path = "../../../common/build-info" }
interactors = { path = "../../../system/interactors" }
sub-systems = { path = "../../../system/sub-systems" }
host-info = { path = "../../../common/host-info" }
key-derivation-traits = { path = "../../../app/key-derivation-traits" }
signing-traits = { path = "../../../app/signing-traits" }
factor-instances-provider = { path = "../../../factors/instances-provider" }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
async-trait = { workspace = true }
actix-rt = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
