[package]
name = "sargon-profile-security-structures"
version = "1.1.99"
edition = "2021"

[dependencies]
# === INTERNAL DEPENDENCIES ===
sargon-core = { path = "../sargon-core" }
identified-vec-of = { path = "../identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-factors = { path = "../sargon-factors" }
sargon-addresses = { path = "../sargon-addresses" }
next-derivation-index-ephemeral = { path = "../next-derivation-index-ephemeral" }

# === RADIX DEPENDENCIES ===
radix-engine-interface = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }