[package]
name = "sargon-profile-security-structures"
version = "1.1.99"
edition = "2021"

[dependencies]
# === INTERNAL DEPENDENCIES ===
identified-vec-of = { path = "../identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-factors = { path = "../sargon-factors" }
sargon-has-sample-values = { path = "../sargon-has-sample-values" }
sargon-addresses = { path = "../sargon-addresses" }
next-derivation-index-ephemeral = { path = "../next-derivation-index-ephemeral" }
sargon-core-network = { path = "../sargon-core-network" }
sargon-core-collections = { path = "../sargon-core-collections" }
sargon-core-time-utils = { path = "../sargon-core-time-utils" }
sargon-core-short-string = { path = "../sargon-core-short-string" }
sargon-core-utils = { path = "../sargon-core-utils" }

# === RADIX DEPENDENCIES ===
radix-engine-interface = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
