[package]
name = "profile-state-holder"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
profile = { path = "../../profile/models/profile_SPLIT_ME" }
error = { path = "../../core/error" }
profile-supporting-types = { path = "../../profile/models/supporting-types" }
profile-logic = { path = "../../profile/logic/logic_SPLIT_ME" }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
