[package]
name = "profile-state-holder"
version = "1.2.11"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
profile = { workspace = true }
error = { workspace = true }
profile-supporting-types = { workspace = true }
profile-logic = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
