[package]
name = "transaction-models"
version = "1.2.9"
edition = "2021"


[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
identified-vec-of = { workspace = true }
hierarchical-deterministic = { workspace = true }
factors = { workspace = true }
addresses = { workspace = true }
hash = { workspace = true }
bytes = { workspace = true }
ecc = { workspace = true }
numeric = { workspace = true }
has-sample-values = { workspace = true }
metadata = { workspace = true }
network = { workspace = true }
core-utils = { workspace = true }
transaction-foundation = { workspace = true }
core-collections = { workspace = true }
core-misc = { workspace = true }                  # Instant
profile-security-structures = { workspace = true }

# === RADIX DEPENDENCIES ===
radix-common = { workspace = true }
radix-common-derive = { workspace = true }
radix-engine = { workspace = true }
radix-engine-interface = { workspace = true }
radix-engine-toolkit = { workspace = true }
radix-engine-toolkit-common = { workspace = true }
radix-rust = { workspace = true }
radix-transactions = { workspace = true }
sbor = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-iterator = { workspace = true }
enum-as-inner = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
either = { workspace = true }

[build-dependencies]
cargo_toml = { workspace = true }
