use crate::prelude::*;

decl_identified_vec_of!(
    /// A collection of [`FactorSource`]s generated by a wallet or manually added by user.
    /// MUST never be empty.
    FactorSource
);

pub trait FactorSourcesWithBDFS {
    fn with_bdfs(device_factor_source: DeviceFactorSource) -> Self;
}

impl FactorSourcesWithBDFS for FactorSources {
    /// Panics if `device_factor_source` is not using Babylon crypto parameters
    fn with_bdfs(device_factor_source: DeviceFactorSource) -> Self {
        Self::just(device_factor_source.into())
    }
}

impl HasSampleValues for FactorSources {
    fn sample() -> Self {
        Self::from_iter([
            FactorSource::sample_device(),
            FactorSource::sample_ledger(),
        ])
    }

    fn sample_other() -> Self {
        Self::from_iter([
            FactorSource::sample_device_olympia(),
            FactorSource::sample_device_babylon(),
        ])
    }
}

#[cfg(test)]
mod tests {

    use super::*;

    #[allow(clippy::upper_case_acronyms)]
    type SUT = FactorSources;

    #[test]
    fn identifiable_id_uses_factor_source_id() {
        assert_eq!(
            FactorSource::sample_device().id(),
            FactorSource::sample_device().factor_source_id()
        )
    }

    #[test]
    fn factor_sources_sample_is_not_empty() {
        assert_eq!(SUT::sample().len(), 2);
        assert_eq!(SUT::sample().get_all().len(), 2);
        assert_eq!(SUT::sample().ids().len(), 2);
        assert!(!SUT::sample().is_empty());
    }

    #[test]
    fn inequality() {
        assert_ne!(SUT::sample(), SUT::sample_other());
    }

    #[test]
    fn duplicates_are_prevented() {
        assert_eq!(
            SUT::from_iter(
                [FactorSource::sample(), FactorSource::sample()].into_iter()
            )
            .len(),
            1
        )
    }

    #[test]
    fn json_serialize_of_empty_factor_sources_is_err() {
        assert!(serde_json::to_value(SUT::new()).is_err());
    }
    #[test]
    fn json_deserialize_of_empty_factor_sources_is_err() {
        assert!(serde_json::from_value::<SUT>(serde_json::Value::Array(
            Vec::new()
        ))
        .is_err());
    }

    #[test]
    fn json_roundtrip_sample() {
        let sut = SUT::sample();
        assert_eq_after_json_roundtrip(
            &sut,
            r#"
            [
                {
                    "discriminator": "device",
                    "device": {
                        "id": {
                            "kind": "device",
                            "body": "f1a93d324dd0f2bff89963ab81ed6e0c2ee7e18c0827dc1d3576b2d9f26bbd0a"
                        },
                        "common": {
                            "flags": [],
                            "addedOn": "2023-09-11T16:05:56.000Z",
                            "cryptoParameters": {
                                "supportedCurves": ["curve25519"],
                                "supportedDerivationPathSchemes": ["cap26"]
                            },
                            "lastUsedOn": "2023-09-11T16:05:56.000Z"
                        },
                        "hint": {
                            "name": "My precious",
                            "model": "iPhone SE 2nd gen",
                            "mnemonicWordCount": 24,
                            "systemVersion": "iOS 17.4.1",
                            "hostAppVersion": "1.6.4",
                            "hostVendor": "Apple"
                        }
                    }
                },
                {
                    "discriminator": "ledgerHQHardwareWallet",
                    "ledgerHQHardwareWallet": {
                        "id": {
                            "kind": "ledgerHQHardwareWallet",
                            "body": "ab59987eedd181fe98e512c1ba0f5ff059f11b5c7c56f15614dcc9fe03fec58b"
                        },
                        "common": {
                            "addedOn": "2023-09-11T16:05:56.000Z",
                            "cryptoParameters": {
                                "supportedCurves": ["curve25519"],
                                "supportedDerivationPathSchemes": ["cap26"]
                            },
                            "flags": [],
                            "lastUsedOn": "2023-09-11T16:05:56.000Z"
                        },
                        "hint": {
                            "name": "Orange, scratched",
                            "model": "nanoS+"
                        }
                    }
                }
            ]
            "#,
        )
    }
}
