[package]
name = "discover"
version = "1.2.28"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
core-utils = { workspace = true }
clients = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
url = { workspace = true }
actix-rt = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
iso8601-timestamp = { workspace = true }
