[package]
name = "sargon-core"
version = "1.2.1"
edition = "2021"

[dependencies]
identified-vec-of = { path = "../identified-vec-of" }
sargon-core-utils = { path = "../sargon-core-utils" }
sargon-core-error = { path = "../sargon-core-error" }
sargon-core-assert-json = { path = "../sargon-core-assert-json" }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }
radix-engine-interface = { workspace = true }
radix-rust = { workspace = true }
radix-transactions = { workspace = true }


# ==== EXTERNAL DEPENDENCIES ====
aes-gcm = { workspace = true }
arraystring = { workspace = true }
assert-json-diff = { workspace = true }
delegate = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
hkdf = { workspace = true }
hex = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
derive_more = { workspace = true }


itertools = { workspace = true }
iota-crypto = { workspace = true }
k256 = { workspace = true }
rand = { workspace = true }
log = { workspace = true }


serde_with = { workspace = true }

paste = { workspace = true }
serde_repr = { workspace = true }
iso8601-timestamp = { workspace = true }
zeroize = { workspace = true }
strum = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }

uuid = { workspace = true }
