[package]
name = "sargon-core"
version = "0.0.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
hkdf = { workspace = true }
assert-json-diff = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
derive_more = { workspace = true }


# SLIP10 implementation
iota-crypto = { workspace = true }
# Transitive dependency of iota_crypto - used to construct PubKey from uncompressed bytes.
k256 = { workspace = true }
rand = { workspace = true }
log = { workspace = true }

radix-rust = { workspace = true }
serde_with = { workspace = true }
enum-as-inner = { workspace = true }
paste = { workspace = true }
serde_repr = { workspace = true }
hex = { workspace = true }
iso8601-timestamp = { workspace = true }
itertools = { workspace = true }
zeroize = { workspace = true }
strum = { workspace = true }
url = { workspace = true }

uuid = { workspace = true }
