[package]
name = "sargon-os-arculus-card"
version = "1.2.29"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
hash = { workspace = true }
sargon-os = { path = "../../../system/os/os" }
error = { workspace = true }
factors = { workspace = true }
ecc = { workspace = true }
hierarchical-deterministic = { workspace = true }
signing-traits = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
async-trait = { workspace = true }
indexmap = { workspace = true }
