[package]
name = "sargon-os-arculus-card"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
sargon-os = { path = "../../../system/os/os" }
error = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
async-trait = { workspace = true }
