[package]
name = "entity-by-address"
version = "1.2.1"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
error = { workspace = true }
addresses = { workspace = true }
profile-account = { workspace = true }
account-for-display = { workspace = true }
entity-for-display = { workspace = true }
persona-for-display = { workspace = true }
profile-account-or-persona = { workspace = true }
profile-persona = { workspace = true }


# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
# None
