[package]
name = "transaction-foundation"
version = "1.2.20"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
has-sample-values = { workspace = true }
bytes = { workspace = true }

# === RADIX DEPENDENCIES ===
radix-engine-interface = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
