[package]
name = "sargon-core-tx"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
sargon-core-assert-json = { path = "../../core/assert-json" }
sargon-has-sample-values = { path = "../../core/has-sample-values" }
sargon-bytes = { path = "../../types/bytes" }

# === RADIX DEPENDENCIES ===
radix-engine-interface = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
