[package]
name = "transaction-foundation"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
assert-json = { path = "../../core/assert-json" }
has-sample-values = { path = "../../core/has-sample-values" }
bytes = { path = "../../common/bytes" }

# === RADIX DEPENDENCIES ===
radix-engine-interface = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
