[package]
name = "profile-base-entity"
version = "1.2.3"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
addresses = { workspace = true }
factors = { workspace = true }
short-string = { workspace = true }
entity-foundation = { workspace = true }
identified-vec-of = { workspace = true }
network = { workspace = true }
has-sample-values = { workspace = true }
transaction-models = { workspace = true }
profile-security-structures = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-iterator = { workspace = true }
enum-as-inner = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
