[package]
name = "profile-base-entity"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
addresses = { path = "../../../crypto/addresses" }
factors = { path = "../../../factors/factors" }
short-string = { path = "../../../common/short-string" }
entity-foundation = { path = "../../../common/entity-foundation" }
identified-vec-of = { path = "../../../common/identified-vec-of" }
network = { path = "../../../common/network" }
has-sample-values = { path = "../../../core/has-sample-values" }
transaction-models = { path = "../../../transaction/models" }
profile-security-structures = { path = "../../../profile/models/security-structures" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-iterator = { workspace = true }
enum-as-inner = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
