[package]
name = "security-center"
version = "1.2.30"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
assert-json = { workspace = true }
addresses = { workspace = true }
has-sample-values = { workspace = true }
core-misc = { workspace = true }
profile-app-preferences = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
serde = { workspace = true }
