[package]
name = "sargon-os-accounts"
version = "1.2.33"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
sargon-os = { path = "../../../system/os/os" }
error = { workspace = true }
core-collections = { workspace = true }
network = { workspace = true }
addresses = { workspace = true }
transaction-models = { workspace = true }
manifests = { workspace = true }
gateway-client-and-api = { workspace = true }
profile-logic = { workspace = true }

# ==== RADIX DEPENDENCIES ====
radix-engine-interface = { workspace = true }
radix-common = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
actix-rt = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
sargon-os-factors = { workspace = true }
