[package]
name = "profile"
version = "1.2.22"
edition = "2021"


[dependencies]
# === INTERNAL DEPENDENCIES ===
prelude = { workspace = true }
encryption = { workspace = true }
identified-vec-of = { workspace = true }
hierarchical-deterministic = { workspace = true }
factors = { workspace = true }
core-misc = { workspace = true }
profile-persona-data = { workspace = true }
entity-foundation = { workspace = true }
has-sample-values = { workspace = true }
keys-collector = { workspace = true }
addresses = { workspace = true }
transaction-models = { workspace = true }
profile-app-preferences = { workspace = true }
account-for-display = { workspace = true }
profile-security-structures = { workspace = true }
time-utils = { workspace = true }
host-info = { workspace = true }
profile-base-entity = { workspace = true }
profile-account-or-persona = { workspace = true }
profile-account = { workspace = true }
profile-persona = { workspace = true }
entity-by-address = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
hkdf = { workspace = true }
k256 = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }

[build-dependencies]
cargo_toml = { workspace = true }
