[package]
name = "sargon-profile"
version = "1.1.99"
edition = "2021"
build = "build.rs"

[dependencies]
# === INTERNAL DEPENDENCIES ===
sargon-encryption = { path = "../../../crypto/encryption" }
identified-vec-of = { path = "../../../types/identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../../../crypto/hd" }
sargon-factors = { path = "../../../factors/factors" }
sargon-core-misc = { path = "../../../core/misc" }
sargon-core-entity = { path = "../../../types/entity-foundation" }
sargon-has-sample-values = { path = "../../../core/has-sample-values" }
sargon-keys-collector = { path = "../../../factors/keys-collector" }
sargon-addresses = { path = "../../../crypto/addresses" }
sargon-transaction-models = { path = "../../../transaction/models" }
sargon-profile-app-preferences = { path = "../../../profile/models/app-preferences" }
sargon-profile-security-structures = { path = "../../../profile/models/security-structures" }
sargon-core-time-utils = { path = "../../../core/time-utils" }
sargon-core-host-info = { path = "../../../types/host-info" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
hkdf = { workspace = true }
k256 = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }

[build-dependencies]
cargo_toml = { workspace = true }
