[package]
name = "profile"
version = "1.1.99"
edition = "2021"
build = "build.rs"

[dependencies]
# === INTERNAL DEPENDENCIES ===
encryption = { path = "../../../crypto/encryption" }
identified-vec-of = { path = "../../../common/identified-vec-of" }
hierarchical-deterministic = { path = "../../../crypto/hd" }
factors = { path = "../../../factors/factors" }
core-misc = { path = "../../../core/misc" }
profile-persona-data = { path = "../../../profile/models/persona-data" }
entity-foundation = { path = "../../../common/entity-foundation" }
has-sample-values = { path = "../../../core/has-sample-values" }
keys-collector = { path = "../../../factors/keys-collector" }
addresses = { path = "../../../crypto/addresses" }
transaction-models = { path = "../../../transaction/models" }
profile-app-preferences = { path = "../../../profile/models/app-preferences" }
account-for-display = { path = "../../../profile/models/account-for-display" }
profile-security-structures = { path = "../../../profile/models/security-structures" }
time-utils = { path = "../../../core/time-utils" }
host-info = { path = "../../../common/host-info" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
hkdf = { workspace = true }
k256 = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }

[build-dependencies]
cargo_toml = { workspace = true }
