[package]
name = "radix-connect-models"
version = "1.1.100"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
error = { workspace = true }
has-sample-values = { workspace = true }
core-misc = { workspace = true }
bytes = { workspace = true }
network = { workspace = true }
addresses = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
serde = { workspace = true }
