[package]
name = "hash"
version = "1.2.30"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
prelude = { workspace = true }
bytes = { workspace = true }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
serde = { workspace = true }
