[package]
name = "sargon-numeric"
version = "1.1.99"
edition = "2021"

[dependencies]
# === INTERNAL DEPENDENCIES ===
sargon-core-error = { path = "../../core/error" }
sargon-has-sample-values = { path = "../../core/has-sample-values" }
sargon-bytes = { path = "../../types/bytes" }

# === RADIX DEPENDENCIES ===
radix-common = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
enum-iterator = { workspace = true }
delegate = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
