[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
TARGET_DIR = { value = "target", relative = true }
FIXTURES = "fixtures"
FIXTURES_TX = "fixtures/transaction"
FIXTURES_VECTOR = "fixtures/vector"
FIXTURES_MODELS = "fixtures/models"
FIXTURES_MODELS_GW = "fixtures/models/gateway"
FIXTURES_MODELS_INTERACTION = "fixtures/models/interaction"
FIXTURES_MODELS_PROFILES = "fixtures/models/profile"
FIXTURES_MODELS_PROFILE = "fixtures/models/profile_submodels"
