[package]
name = "profile-logic"
version = "1.2.5"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
addresses = { workspace = true }
entity-by-address = { workspace = true }
factors = { workspace = true }
hierarchical-deterministic = { workspace = true }
identified-vec-of = { workspace = true }
prelude = { workspace = true }
profile = { workspace = true }
profile-persona = { workspace = true }
profile-supporting-types = { workspace = true }
time-utils = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
itertools = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
