[package]
name = "profile-logic"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
identified-vec-of = { path = "../../../common/identified-vec-of" }
hierarchical-deterministic = { path = "../../../crypto/hd" }
factors = { path = "../../../factors/factors" }
addresses = { path = "../../../crypto/addresses" }
profile = { path = "../../../profile/models/profile_SPLIT_ME" }
profile-supporting-types = { path = "../../../profile/models/supporting-types" }
time-utils = { path = "../../../core/time-utils" }
entity-by-address = { path = "../../../profile/traits/entity-by-address" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
itertools = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
