[package]
name = "sargon-profile-logic"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
identified-vec-of = { path = "../../../types/identified-vec-of" }
sargon-hierarchical-deterministic = { path = "../../../crypto/hd" }
sargon-factors = { path = "../../../factors/factors" }
sargon-addresses = { path = "../../../crypto/addresses" }
sargon-profile = { path = "../../../profile/models/profile_SPLIT_ME" }
sargon-profile-supporting-types = { path = "../../../profile/models/supporting-types" }
sargon-core-time-utils = { path = "../../../core/time-utils" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
derive_more = { workspace = true }
itertools = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
