[package]
name = "sargon-core-network"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
sargon-core-assert-json = { path = "../../core/assert-json" }
sargon-has-sample-values = { path = "../../core/has-sample-values" }
sargon-numeric = { path = "../../types/numeric" }

# === RADIX DEPENDENCIES ===
radix-common = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
enum-iterator = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
serde_repr = { workspace = true }
serde_json = { workspace = true }
