[package]
name = "sargon-factor-instances-provider"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
identified-vec-of = { path = "../identified-vec-of" }
sargon-core-assert-json = { path = "../sargon-core-assert-json" }
sargon-core-utils = { path = "../sargon-core-utils" }
sargon-core-error = { path = "../sargon-core-error" }
sargon-core = { path = "../sargon-core" }
sargon-factors = { path = "../sargon-factors" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-keys-collector = { path = "../sargon-keys-collector" }
sargon-addresses = { path = "../sargon-addresses" }
sargon-profile = { path = "../sargon-profile" }
sargon-profile-logic = { path = "../sargon-profile-logic" }
sargon-clients = { path = "../sargon-clients" }
sargon-profile-supporting-types = { path = "../sargon-profile-supporting-types" }
next-derivation-index-ephemeral = { path = "../next-derivation-index-ephemeral" }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }
