[package]
name = "sargon-factor-instances-provider"
version = "1.2.1"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
identified-vec-of = { path = "../identified-vec-of" }
sargon-core-assert-json = { path = "../sargon-core-assert-json" }
sargon-core-utils = { path = "../sargon-core-utils" }
sargon-core-error = { path = "../sargon-core-error" }
sargon-core = { path = "../sargon-core" }
sargon-factors = { path = "../sargon-factors" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-keys-collector = { path = "../sargon-keys-collector" }
sargon-addresses = { path = "../sargon-addresses" }
sargon-profile = { path = "../sargon-profile" }
sargon-clients = { path = "../sargon-clients" }
sargon-profile-supporting-types = { path = "../sargon-profile-supporting-types" }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }
radix-engine-interface = { workspace = true }
radix-rust = { workspace = true }
radix-transactions = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
aes-gcm = { workspace = true }
arraystring = { workspace = true }
assert-json-diff = { workspace = true }
delegate = { workspace = true }
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
enum-iterator = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
iota-crypto = { workspace = true }
iso8601-timestamp = { workspace = true }
itertools = { workspace = true }
k256 = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }
