import CustomDump
import Foundation
import Sargon
import SargonUniFFI
import XCTest

class FileSystemDriverTests: DriverTest<FileSystem> {
	
	func test() async throws {
		let nameOfFile = "delete_me_\(UUID().uuidString).txt"
		let path = URL.temporaryDirectory.appending(path: nameOfFile, directoryHint: .notDirectory).path()
		let data = Data("This file is completely safe to delete. It was generated by a unit test.".utf8)
		
		let sut = SUT()
        try await sut.saveToFile(path: path, data: data, isAllowedToOverwrite: true)
		let loaded = try await sut.loadFromFile(path: path)
		XCTAssertEqual(loaded, data)
		
		XCTAssertTrue(FileManager.default.fileExists(atPath: path))
		try await sut.deleteFile(path: path)
		XCTAssertFalse(FileManager.default.fileExists(atPath: path))
	}
    
    func test_without_overwrite() async throws {
        let nameOfFile = "delete_me_\(UUID().uuidString).txt"
        let path = URL.temporaryDirectory.appending(path: nameOfFile, directoryHint: .notDirectory).path()
        let data = Data("This file is completely safe to delete. It was generated by a unit test.".utf8)
        
        let sut = SUT()
        try await sut.saveToFile(path: path, data: data, isAllowedToOverwrite: true)
        do {
            try await sut.saveToFile(path: path, data: data, isAllowedToOverwrite: false)
            XCTFail("Expected throw")
        } catch {
            // Good, expected to throw
        }
    }
}
