[package]
name = "home-cards"
version = "1.2.18"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
identified-vec-of = { workspace = true }
addresses = { workspace = true }
bytes = { workspace = true }
core-utils = { workspace = true }
network = { workspace = true }
metadata = { workspace = true }
drivers = { workspace = true }
gateway-client-and-api = { workspace = true }
gateway-models = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
actix-rt = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
