[package]
name = "sargon-ecc"
version = "1.1.99"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
sargon-has-sample-values = { path = "../sargon-has-sample-values" }
sargon-core-error = { path = "../sargon-core-error" }
sargon-core-assert-json = { path = "../sargon-core-assert-json" }
sargon-bytes = { path = "../sargon-bytes" }
sargon-hash = { path = "../sargon-hash" }
identified-vec-of = { path = "../identified-vec-of" }

# ==== RADIX DEPENDENCIES ====
radix-common = { workspace = true }
radix-transactions = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
derive_more = { workspace = true }
enum-as-inner = { workspace = true }
hex = { workspace = true }
iota-crypto = { workspace = true }
k256 = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
zeroize = { workspace = true }
