[package]
name = "sargon-drivers"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
sargon-core = { path = "../sargon-core" }
sargon-hierarchical-deterministic = { path = "../sargon-hierarchical-deterministic" }
sargon-addresses = { path = "../sargon-addresses" }
sargon-profile = { path = "../sargon-profile" }
sargon-profile-supporting-types = { path = "../sargon-profile-supporting-types" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
async-trait = { workspace = true }
derive_more = { workspace = true }
enum-iterator = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }
