[package]
name = "time-utils"
version = "1.2.22"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
# None besides 'prelude'
prelude = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
iso8601-timestamp = { workspace = true }
serde_json = { workspace = true }
