[package]
name = "interaction-queue-models"
version = "1.2.1"
edition = "2024"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
core-utils = { workspace = true }
transaction-models = { workspace = true }
gateway-models = { workspace = true }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
actix-rt = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
async-std = { workspace = true }
futures = { workspace = true }
