[package]
name = "has-sample-values"
version = "1.2.18"
edition = "2021"

[dependencies]
error = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
indexmap = { workspace = true }
iso8601-timestamp = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
