[package]
name = "sargon-core-short-string"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
identified-vec-of = { path = "../../types/identified-vec-of" }
sargon-core-assert-json = { path = "../../core/assert-json" }
sargon-core-utils = { path = "../../core/utils" }
sargon-has-sample-values = { path = "../../core/has-sample-values" }

# === RADIX DEPENDENCIES ===
# None

# === EXTERNAL DEPENDENCIES ===
arraystring = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
