[package]
name = "signing-traits"
version = "1.2.30"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
prelude = { workspace = true }
error = { workspace = true }
ecc = { workspace = true }
enum-as-inner = { workspace = true }
core-collections = { workspace = true }
bytes = { workspace = true }
hash = { workspace = true }
radix-connect-models = { workspace = true }
transaction-models = { workspace = true }
entity-by-address = { workspace = true }
profile-account-or-persona = { workspace = true }
profile-persona = { workspace = true }
profile-account = { workspace = true }
metadata = { workspace = true }

# === RADIX DEPENDENCIES ===
radix-engine-interface = { workspace = true }
radix-transactions = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
async-trait = { workspace = true }
derive_more = { workspace = true }
indexmap = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
