[package]
name = "signing-traits"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
error = { path = "../../core/error" }
ecc = { path = "../../crypto/ecc" }
core-collections = { path = "../../core/collections" }
bytes = { path = "../../common/bytes" }
hash = { path = "../../crypto/hash" }
radix-connect-models = { path = "../../app/radix-connect-models" }
transaction-models = { path = "../../transaction/models" }
entity-by-address = { path = "../../profile/traits/entity-by-address" }
profile-account-or-persona = { path = "../../profile/models/account-or-persona" }
profile-persona = { path = "../../profile/models/persona" }
profile-account = { path = "../../profile/models/account" }
metadata = { path = "../../common/metadata" }

# === RADIX DEPENDENCIES ===
radix-engine-interface = { workspace = true }
radix-transactions = { workspace = true }

# === EXTERNAL DEPENDENCIES ===
async-trait = { workspace = true }
derive_more = { workspace = true }
indexmap = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
