[package]
name = "encryption"
version = "1.1.99"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
has-sample-values = { path = "../../core/has-sample-values" }
error = { path = "../../core/error" }
assert-json = { path = "../../core/assert-json" }
bytes = { path = "../../common/bytes" }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
aes-gcm = { workspace = true }
derive_more = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
iota-crypto = { workspace = true }
k256 = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
zeroize = { workspace = true }
