[package]
name = "encryption"
version = "1.2.12"
edition = "2021"

[dependencies]
# ==== INTERNAL DEPENDENCIES ====
prelude = { workspace = true }
has-sample-values = { workspace = true }
error = { workspace = true }
assert-json = { workspace = true }
bytes = { workspace = true }

# ==== RADIX DEPENDENCIES ====
# None

# ==== EXTERNAL DEPENDENCIES ====
aes-gcm = { workspace = true }
derive_more = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
iota-crypto = { workspace = true }
k256 = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
zeroize = { workspace = true }
