name: CD Desktop Binaries

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: "A custom version name. The resulting name will have the format <cargo.version.patch>-<custom-name>-<rev> (E.g. 1.0.23-custom-name-2eb68d8c)."
        required: false
        type: string
  push:
    tags:
      - "**"
    branches:
      - main
      - ci/ubuntu-runners

permissions:
  id-token: write
  contents: write
  packages: write
env:
  CARGO_TERM_COLOR: always
  MACHINE: ubuntu-latest
jobs:
  build:
    strategy:
      matrix:
        build-target:
          - runner: ubuntu-latest
            toolchain: x86_64-unknown-linux-gnu
            binary: libsargon.so
          - runner: macos-latest
            toolchain: aarch64-apple-darwin
            binary: libsargon.dylib
    runs-on: ${{ matrix.build-target.runner }}
    env:
      RUST_TOOLCHAIN: nightly-2024-01-11
      RUST_COMPONENTS: "rust-std"
      CUSTOM_BUILD_NAME: "test"
    steps:
      - uses: RDXWorks-actions/checkout@main

      - name: Install Rust Toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: ${{ env.RUST_COMPONENTS }}
          target: ${{ matrix.build-target.toolchain }}

      - name: Build and publish Desktop binaries
        uses: RDXWorks-actions/gradle-build-action@main
        with:
          arguments: sargon-desktop:assemble -PbuildType=release
          build-root-directory: jvm

      - name: Upload Artifacts
        uses: RDXWorks-actions/upload-artifact@main
        with:
          path: "target/${{ matrix.build-target.toolchain }}/release/${{ matrix.build-target.binary }}"
