name: CD

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: macos-13-xlarge
    steps:
      - uses: RDXWorks-actions/checkout@main
      - name: Install Rust Toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: nightly-2024-01-11
          default: true
      - name: Run iOS build script
        run: |
            zip_path = ./scripts/ios/release.sh
        