name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: macos-13-xlarge
    steps:
      - uses: RDXWorks-actions/checkout@main

      - name: Install Rust Toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: nightly-2024-01-11
          default: true
          target: ${{ matrix.build-target.target-triple }}
          components: rust-std

      - name: Run iOS build script
        run: |
          rustup target add x86_64-apple-ios aarch64-apple-ios arch64-apple-ios-sim
          sh ./scripts/ios/release.sh
