name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        build-target:
          - target-triple: x86_64-apple-ios
            runner: macos-13-xlarge
          - target-triple: aarch64-apple-ios
            runner: macos-13-xlarge
          - target-triple: aarch64-apple-ios-sim
            runner: macos-13-xlarge
    runs-on: ${{ matrix.build-target.runner }}
    steps:
      - uses: RDXWorks-actions/checkout@main

      - name: Install Rust Toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: nightly-2024-01-11
          default: true
          target: ${{ matrix.build-target.target-triple }}
          components: rust-std

      - name: Install rust target
        run: rustup target add ${{ matrix.build-target.target-triple }}
      
      - name: Run iOS build script
        run: |
            sh ./scripts/ios/release.sh
