name: CD Desktop Binaries

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: "A custom version name. The resulting name will have the format <cargo.version.patch>-<custom-name>-<rev> (E.g. 1.0.23-custom-name-2eb68d8c)."
        required: false
        type: string
  push:
    tags:
      - "**"
    branches:
      - main
      - ci/ubuntu-runners

permissions:
  id-token: write
  contents: write
  packages: write
env:
  CARGO_TERM_COLOR: always
  MACHINE: ubuntu-latest
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: nightly-2024-01-11
      RUST_COMPONENTS: "rust-std"
      CUSTOM_BUILD_NAME: "test"
    steps:
      - uses: RDXWorks-actions/checkout@main

      - name: Install Rust Toolchain for x86_64-unknown-linux-gnu
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: ${{ env.RUST_COMPONENTS }}
          target: x86_64-unknown-linux-gnu

      - name: Set up JDK 17
        uses: RDXWorks-actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Prune Tags
        run: git fetch --prune --tags

      - name: Build and publish Desktop binaries
        uses: RDXWorks-actions/gradle-build-action@main
        with:
          arguments: sargon-desktop:publish -PbuildType=release
          build-root-directory: jvm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
