name: CD JVM

on:
  workflow_dispatch:
  push:
    branches:
      - android

permissions:
  id-token: write
  contents: write
  packages: write
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: macos-13-xlarge
    env:
      RUST_TOOLCHAIN: nightly-2024-01-11
      RUST_COMPONENTS: "rust-std"
    steps:
      - uses: RDXWorks-actions/checkout@main

      - name: Install Rust Toolchain for aarch64-linux-android
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: ${{ env.RUST_COMPONENTS }}
          target: aarch64-linux-android
          
      - name: Install Rust Toolchain for armv7-linux-androideabi
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: ${{ env.RUST_COMPONENTS }}
          target: armv7-linux-androideabi

      - name: Install Rust Toolchain for aarch64-apple-darwin
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: ${{ env.RUST_COMPONENTS }}
          target: aarch64-apple-darwin

      - name: Install Rust Toolchain for x86_64-apple-darwin
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: ${{ env.RUST_COMPONENTS }}
          target: x86_64-apple-darwin

      - name: Set up JDK 17
        uses: RDXWorks-actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: RDXWorks-actions/setup-android@v2
      
      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Setup Env Variables
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        run: |
          git fetch --prune --tags
          echo "SARGON_VERSION=`git tag --sort=taggerdate | tail -1`-`git rev-parse --short @`" >> $GITHUB_ENV
          echo $SARGON_VERSION

      - name: Build and publish Android
        uses: RDXWorks-actions/gradle-build-action@main
        with:
          arguments: sargon-android:publish
          build-root-directory: jvm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Desktop binaries
        uses: RDXWorks-actions/gradle-build-action@main
        with:
          arguments: sargon-desktop-bins:publish
          build-root-directory: jvm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      