[package]
name = "sargon-os-transaction"
version = "1.1.99"
edition = "2021"

[dependencies]
# === SARGON CRATES ===
sargon-os = { path = "../../../system/os/os" }
transaction-models = { path = "../../../transaction/models" }
manifests = { path = "../../../transaction/manifests" }
signing-traits = { path = "../../../app/signing-traits" }
radix-connect-models = { path = "../../../app/radix-connect-models" }
signing = { path = "../../../app/signing" }
entity-by-address = { path = "../../../profile/traits/entity-by-address" }
profile = { path = "../../../profile/models/profile_SPLIT_ME" }
# profile-state-holder = { path = "../../../system/profile-state-holder" }
profile-account-or-persona = { path = "../../../profile/models/account-or-persona" }
gateway-client-and-api = { path = "../../../gateway/client-and-api" }

# ==== RADIX DEPENDENCIES ====
radix-engine-interface = { workspace = true }
radix-engine-toolkit-common = { workspace = true }
radix-common = { workspace = true }

# ==== EXTERNAL DEPENDENCIES ====
actix-rt = { workspace = true }
async-std = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
